### ISSUE TITLE
Errors in the make file maybe?

### ISSUE THREAD

**Issue by eduOS** [th0rgall/voc-enhancer#14]
How to use this source code repository? I run makefile and am stopped by these errors: 

> ./makefile: 1: ./makefile: default:: not found
> ./makefile: 3: ./makefile: SHELL: not found
> ./makefile: 5: ./makefile: CP_COMMON_SOURCES: not found
> ./makefile: 6: ./makefile: BROWSERIFY_API: not found
> ./makefile: 8: ./makefile: build:: not found
> ./makefile: 10: ./makefile: build_ff:: not found
> ./makefile: 12: ./makefile: dist/firefox: Permission denied
> ./makefile: 13: ./makefile: dist/firefox/api/vocabulary-api.js: not found
> npm ERR! could not determine executable to run
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/lerner/.npm/_logs/2021-08-09T23_14_57_621Z-debug.log
> ./makefile: 16: ./makefile: build_chr:: not found
> ./makefile: 18: ./makefile: dist/chrome: Permission denied
> ./makefile: 19: ./makefile: dist/chrome/api/vocabulary-api.js: not found
> npm ERR! could not determine executable to run
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/lerner/.npm/_logs/2021-08-09T23_14_59_796Z-debug.log
> ./makefile: 22: ./makefile: pack_ff:: not found
> ./makefile: 24: ./makefile: pushd: not found
> ./makefile: 24: ./makefile: popd: not found
> ./makefile: 26: ./makefile: pack_chr:: not found
> ./makefile: 33: ./makefile: pushd: not found
> ./makefile: 33: ./makefile: popd: not found
> ./makefile: 35: ./makefile: clean:: not found
> ./makefile: 37: ./makefile: clean_ff:: not found
> ./makefile: 41: ./makefile: clean_chr:: not found
> ./makefile: 45: ./makefile: pack_src:: not found

**Comment by th0rgall** [comment]
Ah, I guess you ran the makefile as a shell command, and not with the program [`make`](https://www.gnu.org/software/make/)? Good luck diving in the code here!
