### ISSUE TITLE
Not working on FF 78.0.2

### ISSUE THREAD

**Issue by slonm** [th0rgall/voc-enhancer#5]
My environment: MS Windows 10 64x. FF 78.0.2 64bit.
Extension installed and do nothing on select word on the page

**Comment by th0rgall** [comment]
Hey @slonm, thanks for the report. Just checking a few things before investigating further:

- Did you restart your browser after installing the extension? There is a known bug that it might not work directly after install.
- I assume you right-clicked a text selection to see the extensions' options?
- I assume you have a vocabulary.com account and you're logged in on the site?

I can rule out a breaking API change of vocabulary.com, the extension still works here (FF Mobile for Android. It might

**Comment by slonm** [comment]
>Did you restart your browser after installing the extension? There is a known bug that it might not work directly after install.

Yes

> I assume you right-clicked a text selection to see the extension's options?

Yes. See screenshot 
![image](https://user-images.githubusercontent.com/951663/88134219-b786b300-cbec-11ea-95b4-1e1f71d9b67a.png)

>I assume you have a vocabulary.com account and you're logged in on the site?

I had not but i created it for test. Popups still absent

**Comment by th0rgall** [comment]
Thanks for the screenshot! Actually, it shows expected functionality. There is not supposed to be a pop-up there.

The only functionality that exists currently on a selection right-click is what you see: the "add word to a list" functionality. It is the bottom-most entry in the context menu (`voc.com: add 'considered' to ...`)

Are you expecting a pop-up with a definition or translation to appear on any web page? That isn't implemented now. Translations are only injected when you play a game on vocabulary.com itself (see the [full add-on description](https://addons.mozilla.org/en-US/firefox/addon/vocabulary-com-enhancer/))

I can mark a "definition/translation pop-up on any page" as a feature request though, I imagine more users would like this.

**Comment by slonm** [comment]
Sorry. I mistook as popup baloon comments on screenshots. Basically i was search "translation in the popup" extension.
